from_nsq:
  nsqlookupd_address: your_address:your_port
  memory_mes: 1000
  disk_mes: 1000
to_nsq:
  test_message_period: 5   #in minutes
  polling_period: 1        #in minutes
  topic: memory_checker
  producer: your_address:your_port
  
    